title: IIIF Gallery Builder Tutorial
description: Learn how to create, save, and share IIIF image galleries using the Gallery Builder tool.
theme: just-the-docs

url: https://davidrumseymapcenter.github.io/gallery-builder-tutorial
baseurl: /gallery-builder-tutorial

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-include-cache
