title: IIIF Gallery Builder Tutorial
description: How to create, save, and share IIIF image galleries using the Gallery Builder tool.
theme: just-the-docs

url: https://davidrumseymapcenter.github.io/gallery-builder-tutorial

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout 
