title: IIIF Gallery Builder
description: Learn how to create, save, and share IIIF image galleries using the Gallery Builder tool.
theme: just-the-docs

url: https://davidrumseymapcenter.github.io/gallery-builder-tutorial/docs
baseurl: /gallery-builder-tutorial/docs

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-include-cache
