title: IIIF Gallery Builder
description: Learn how to create, save, and share IIIF image galleries using the Gallery Builder tool.
theme: just-the-docs

url: https://davidrumseymapcenter.github.io
baseurl: /gallery-builder-tutorial

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-include-cache

enable_copy_code_button: true
