title: IIIF Gallery Builder
description: Learn how to create, save, and share IIIF image galleries using the Gallery Builder tool.
theme: just-the-docs

url: https://davidrumseymapcenter.github.io
baseurl: /gallery-builder-tutorial

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-include-cache

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: Next step
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

footer_content: "Authored by the [David Rumsey Map Center](https://library.stanford.edu/libraries/david-rumsey-map-center){:target="_blank"}, 2026. | Built with Jekyll and Just the Docs"

back_to_top: true
back_to_top_text: "Back to top" 

enable_copy_code_button: true
